rarity:
  COMMON: '&7Comum'
  UNCOMMON: '&aIncomum'
  RARE: '&9Raro'
  EPIC: '&5Épico'
  LEGENDARY: '&6Lendário'
  DIVINE: '&dDivino'

messages:
  custom-items-usage: '&cUso correto: /customitem <id>'
  invalid-item: '&cVocê precisa estar segurando um item na mão.'
  not-custom-item: '&cO item na sua mão não é um item customizado.'
  reseted-item: '&aItem resetado com sucesso.'
  list:
    - ''
    - '&7&lItens customizados'
    - ''
  list-item: '&7- &f%item-id% &7(%item-rarity%&7)'
  give-usage: '&cUso correto: /customitem give <player> <item-id>'
  invalid-player: '&cJogador inválido.'
  invalid-custom-item: '&cItem customizado inválido.'
  given-item: '&aItem customizado entregue com sucesso.'
  delete-usage: '&cUso correto: /customitem delete <item-id>'
  custom-item-deleted: '&aItem customizado deletado com sucesso.'
  help:
    - ''
    - '&7&lComandos de itens customizados'
    - ''
    - '&7/customitem (id) &f- &7Cria um item customizado.'
    - '&7/customitem give (player) <item-id> &f- &7Entrega um item customizado para um jogador.'
    - '&7/customitem delete <item-id> &f- &7Deleta um item customizado.'
    - '&7/customitem list &f- &7Lista todos os itens customizados.'
    - '&7/customitem reset &f- &7Reseta o item customizado que você está segurando.'
    - '&7/customitem help &f- &7Mostra todos os comandos de itens customizados.'
    - ''